package physique;

public interface InterfaceCarte {

	public String baselevel = 
			"WWWWWWWWWWWWWWW"+
			"WWLLLLLLLWLLLLW"+
			"WLLLLLLLLLWLLLW"+
			"WWLLLLLLLWLLLLW"+
			"WLLLLLWLLLLLLLW"+
			"WWLLLLLLLWLLLLW"+
			"WLLWLWLWLWLLLLW"+
			"WWLLLLLLLLLLLLW"+
			"WLLLWLLLLLLLLLW"+
			"WLLLLLLLLLLLLLW"+
			"WLLLLLLWWWWWWWW"+
			"WLLLLLLLLLLLLLW"+
			"WLWWLLLLLLLLLLW"+
			"WLLLLLLLLLLLLLW"+
			"WLLLLLLLLLLLLLW"+
			"WLLLLLLLLLLLLLW"+
			"WLLLLLLLLLLLLLW"+
			"WWWWWWWWWWWWWWW";
		
}
